Task 3. Bash basics
Anton-Koniouchevsky/quote-service pull request #3
Opened 2021-05-16 15:31 UTC by Anton-Koniouchevsky

- [x] All commands of db.sh and build-client.sh work without issues.

2021-05-20 13:54 UTC, 375291601334 requested changes

2021-05-20 13:54 UTC, 375291601334 commented on scripts/db.sh
> +DBFile="$location/data/users.db"
Мне кажется вот такой вариант лучше т.к. ты не хардкодишь location,  а получаешь его програмно.  У меня при скачивании твоего проекта другой путь, всё ломается, надо лезть руками править
```bash
currentDirectory=$( cd $(dirname "${0}") && pwd)
location=${currentDirectory%scripts}
DBFile="$location/data/users.db"
```

2021-05-20 13:54 UTC, 375291601334 commented on scripts/db.sh
> +}
можно один раз вызвать echo со всем текстом сразу - echo сохраняет исходное форматирование.

2021-05-20 13:54 UTC, 375291601334 commented on scripts/db.sh
> +          exit 1 ;;
я бы добавила *) echo "Only y or n allowed!";;

2021-05-20 13:54 UTC, 375291601334 commented on scripts/db.sh
> +  fi
В задании указано - If there is more than one user with such username, print all
found entries. Твоя реализация выводит только первого нашедшегося.

2021-05-20 13:54 UTC, 375291601334 commented on scripts/db.sh
> +}
![image](https://user-images.githubusercontent.com/33834629/118989849-088d4200-b98b-11eb-8e8e-062b06bf6b20.png)
У тебя не меняется порядок пользователей, меняются только цифры

2021-05-20 13:54 UTC, 375291601334 commented on scripts/build-client.sh
> +buildArchive="$distLocation/client-app.zip"
с путями та же проблема, что и в db.sh

2021-05-20 13:54 UTC, 375291601334 commented on scripts/build-client.sh
> +npm --prefix $sourceLocation run build:$ENV_CONFIGURATION
я бы добавила обработку случаев когда ENV_CONFIGURATION нет в .env файле или они не равны dev или prod

2021-05-20 19:01 UTC, Anton-Koniouchevsky commented on scripts/build-client.sh
> +npm --prefix $sourceLocation run build:$ENV_CONFIGURATION
done

2021-05-20 19:01 UTC, Anton-Koniouchevsky commented on scripts/db.sh
> +}
done

2021-05-20 19:01 UTC, Anton-Koniouchevsky commented on scripts/db.sh
> +          exit 1 ;;
done

2021-05-20 19:01 UTC, Anton-Koniouchevsky commented on scripts/db.sh
> +  fi
done

2021-05-20 19:01 UTC, Anton-Koniouchevsky commented on scripts/db.sh
> +}
done

2021-05-20 19:02 UTC, Anton-Koniouchevsky commented on scripts/db.sh
> +DBFile="$location/data/users.db"
done

2021-05-20 19:02 UTC, Anton-Koniouchevsky commented on scripts/build-client.sh
> +buildArchive="$distLocation/client-app.zip"
done

2021-05-24 13:04 UTC, 375291601334 approved these changes

2021-05-24 14:47 UTC, merged